"""
Report Generator for BugScanner.
Produces professional PDF and Markdown reports in HackerOne/Bugcrowd style.
"""

import json
import os
import re
from datetime import datetime
from pathlib import Path
from typing import Optional

from jinja2 import Environment, FileSystemLoader, select_autoescape


SEVERITY_ORDER = {"CRITICAL": 0, "HIGH": 1, "MEDIUM": 2, "LOW": 3, "INFO": 4}


class ReportGenerator:
    """
    Generates scan reports in Markdown and PDF formats.

    Usage:
        gen = ReportGenerator(findings, meta, output_dir=Path("./reports"))
        md_path = gen.generate_markdown()
        pdf_path = gen.generate_pdf()
    """

    def __init__(
        self,
        findings: list[dict],
        meta: dict,
        output_dir: Path,
    ):
        # Sort findings by severity
        self.findings = sorted(
            [f if isinstance(f, dict) else f.to_dict() for f in findings],
            key=lambda x: SEVERITY_ORDER.get(x.get("severity", "INFO"), 99),
        )
        self.meta = meta
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

        # Template directory
        self._tmpl_dir = Path(__file__).parent / "templates"

        # Jinja2 environment
        self._jinja = Environment(
            loader=FileSystemLoader(str(self._tmpl_dir)),
            autoescape=select_autoescape(["html", "xml"]),
            trim_blocks=True,
            lstrip_blocks=True,
        )
        self._jinja.filters["severity_badge"] = self._severity_badge
        self._jinja.filters["cvss_color"] = self._cvss_color

    # ── Template context ───────────────────────────────────────────────────────

    def _build_context(self) -> dict:
        counts = {"CRITICAL": 0, "HIGH": 0, "MEDIUM": 0, "LOW": 0, "INFO": 0}
        for f in self.findings:
            sev = f.get("severity", "INFO")
            counts[sev] = counts.get(sev, 0) + 1

        risk_score = (
            counts["CRITICAL"] * 10
            + counts["HIGH"] * 7
            + counts["MEDIUM"] * 4
            + counts["LOW"] * 1
        )

        if risk_score >= 20:
            overall_risk = "CRITICAL"
        elif risk_score >= 10:
            overall_risk = "HIGH"
        elif risk_score >= 5:
            overall_risk = "MEDIUM"
        elif risk_score >= 1:
            overall_risk = "LOW"
        else:
            overall_risk = "INFO"

        return {
            "findings": self.findings,
            "meta": self.meta,
            "counts": counts,
            "overall_risk": overall_risk,
            "risk_score": risk_score,
            "report_date": datetime.now().strftime("%Y-%m-%d %H:%M UTC"),
            "total": len(self.findings),
        }

    @staticmethod
    def _severity_badge(severity: str) -> str:
        colors = {
            "CRITICAL": "#d32f2f",
            "HIGH": "#f44336",
            "MEDIUM": "#ff9800",
            "LOW": "#2196f3",
            "INFO": "#9e9e9e",
        }
        return colors.get(severity, "#9e9e9e")

    @staticmethod
    def _cvss_color(score: float) -> str:
        if score >= 9.0:
            return "#d32f2f"
        elif score >= 7.0:
            return "#f44336"
        elif score >= 4.0:
            return "#ff9800"
        elif score > 0:
            return "#2196f3"
        return "#9e9e9e"

    # ── Markdown report ────────────────────────────────────────────────────────

    def generate_markdown(self) -> Path:
        """Generate a Markdown report and return the file path."""
        ctx = self._build_context()
        try:
            tmpl = self._jinja.get_template("report.md.j2")
            content = tmpl.render(**ctx)
        except Exception:
            # Fallback: generate markdown without Jinja2
            content = self._generate_markdown_fallback(ctx)

        ts = datetime.now().strftime("%Y%m%d_%H%M%S")
        out_path = self.output_dir / f"bugscanner_report_{ts}.md"
        out_path.write_text(content, encoding="utf-8")
        return out_path

    def _generate_markdown_fallback(self, ctx: dict) -> str:
        """Generate Markdown without Jinja2 template (inline fallback)."""
        lines = []
        meta = ctx["meta"]
        counts = ctx["counts"]

        lines += [
            "# BugScanner Security Assessment Report",
            "",
            f"> **Target:** `{meta.get('target', 'N/A')}`  ",
            f"> **Date:** {ctx['report_date']}  ",
            f"> **Scanner Version:** {meta.get('scanner_version', '1.0.0')}  ",
            f"> **Overall Risk:** **{ctx['overall_risk']}**  ",
            "",
            "---",
            "",
            "## ⚠️ Ethical Use Disclaimer",
            "",
            "> This report was generated by BugScanner for **authorized security testing only**.",
            "> Unauthorized use is illegal. Always obtain written permission before testing.",
            "",
            "---",
            "",
            "## Executive Summary",
            "",
            f"A security assessment was conducted against `{meta.get('target', 'N/A')}` on {ctx['report_date']}.",
            f"The scanner ran the following modules: {', '.join(meta.get('modules_run', []))}.",
            f"The scan completed in **{meta.get('duration_seconds', 0):.2f} seconds**.",
            "",
            "### Findings Summary",
            "",
            "| Severity | Count |",
            "|----------|-------|",
            f"| 🔴 CRITICAL | {counts['CRITICAL']} |",
            f"| 🟠 HIGH | {counts['HIGH']} |",
            f"| 🟡 MEDIUM | {counts['MEDIUM']} |",
            f"| 🔵 LOW | {counts['LOW']} |",
            f"| ⚪ INFO | {counts['INFO']} |",
            f"| **Total** | **{ctx['total']}** |",
            "",
            "---",
            "",
            "## Technical Findings",
            "",
        ]

        for i, finding in enumerate(ctx["findings"], 1):
            sev = finding.get("severity", "INFO")
            emoji = {"CRITICAL": "🔴", "HIGH": "🟠", "MEDIUM": "🟡", "LOW": "🔵", "INFO": "⚪"}.get(sev, "⚪")

            lines += [
                f"### [{i}] {emoji} {finding.get('title', 'Unknown')}",
                "",
                f"| Field | Value |",
                f"|-------|-------|",
                f"| **Severity** | {sev} |",
                f"| **CVSS Score** | {finding.get('cvss_score', 0.0):.1f} |",
                f"| **CVSS Vector** | `{finding.get('cvss_vector', '')}` |",
                f"| **OWASP Category** | {finding.get('owasp', '')} |",
                f"| **CWE** | {finding.get('cwe', '')} |",
                f"| **URL** | `{finding.get('url', '')}` |",
                f"| **Parameter** | `{finding.get('parameter', '')}` |",
                f"| **Confirmed** | {'✅ Yes' if finding.get('confirmed') else '⚠️ Potential'} |",
                "",
                "#### Description",
                "",
                finding.get("description", ""),
                "",
                "#### Impact",
                "",
                finding.get("impact", ""),
                "",
                "#### Proof of Concept",
                "",
                f"**Payload:**",
                f"```",
                finding.get("payload", ""),
                "```",
                "",
            ]

            # Evidence block
            evidence = finding.get("evidence")
            if evidence:
                lines += [
                    "**Request/Response:**",
                    "",
                    f"```http",
                    f"{evidence.get('method', 'GET')} {evidence.get('url', '')}",
                ]
                for k, v in (evidence.get("request_headers") or {}).items():
                    lines.append(f"{k}: {v}")
                if evidence.get("request_body"):
                    lines += ["", evidence["request_body"][:500]]
                lines += [
                    "```",
                    "",
                    f"```http",
                    f"HTTP/1.1 {evidence.get('status_code', '')}",
                ]
                for k, v in list((evidence.get("response_headers") or {}).items())[:10]:
                    lines.append(f"{k}: {v}")
                lines += [
                    "",
                    (evidence.get("response_body") or "")[:1000],
                    "```",
                    "",
                ]

            lines += [
                "#### Remediation",
                "",
                finding.get("remediation", ""),
                "",
                "#### References",
                "",
            ]
            for ref in finding.get("references", []):
                lines.append(f"- {ref}")
            lines += ["", "---", ""]

        lines += [
            "## Remediation Checklist",
            "",
            "| # | Finding | Severity | Status |",
            "|---|---------|----------|--------|",
        ]
        for i, finding in enumerate(ctx["findings"], 1):
            lines.append(f"| {i} | {finding.get('title', '')[:60]} | {finding.get('severity', '')} | ☐ Open |")

        lines += [
            "",
            "---",
            "",
            "## Disclaimer",
            "",
            "This report was generated by BugScanner for authorized security testing.",
            "All findings should be validated manually before remediation.",
            "CVSS scores are automated estimates — adjust based on your environment.",
            "",
            f"*Report generated: {ctx['report_date']} by BugScanner v{meta.get('scanner_version', '1.0.0')}*",
        ]

        return "\n".join(lines)

    # ── PDF report ─────────────────────────────────────────────────────────────

    def generate_pdf(self) -> Path:
        """Generate a PDF report and return the file path."""
        ts = datetime.now().strftime("%Y%m%d_%H%M%S")
        out_path = self.output_dir / f"bugscanner_report_{ts}.pdf"

        # Try weasyprint first, then reportlab
        try:
            return self._generate_pdf_weasyprint(out_path)
        except ImportError:
            pass
        try:
            return self._generate_pdf_reportlab(out_path)
        except ImportError:
            raise RuntimeError(
                "PDF generation requires weasyprint or reportlab. "
                "Run: pip install weasyprint  OR  pip install reportlab"
            )

    def _generate_pdf_weasyprint(self, out_path: Path) -> Path:
        """Generate PDF using WeasyPrint."""
        from weasyprint import HTML, CSS

        ctx = self._build_context()
        try:
            tmpl = self._jinja.get_template("report.html.j2")
            html_content = tmpl.render(**ctx)
        except Exception:
            html_content = self._generate_html_fallback(ctx)

        HTML(string=html_content).write_pdf(str(out_path))
        return out_path

    def _generate_pdf_reportlab(self, out_path: Path) -> Path:
        """Generate PDF using ReportLab (fallback)."""
        from reportlab.lib.pagesizes import letter, A4
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.units import inch
        from reportlab.lib import colors
        from reportlab.platypus import (
            SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
            HRFlowable, KeepTogether,
        )
        from reportlab.lib.enums import TA_LEFT, TA_CENTER

        ctx = self._build_context()
        doc = SimpleDocTemplate(str(out_path), pagesize=A4, topMargin=0.75*inch, bottomMargin=0.75*inch)
        styles = getSampleStyleSheet()

        # Custom styles
        title_style = ParagraphStyle("Title", parent=styles["Title"], fontSize=24, textColor=colors.HexColor("#1a237e"))
        h1_style = ParagraphStyle("H1", parent=styles["Heading1"], fontSize=16, textColor=colors.HexColor("#1565c0"))
        h2_style = ParagraphStyle("H2", parent=styles["Heading2"], fontSize=13, textColor=colors.HexColor("#1976d2"))
        body_style = ParagraphStyle("Body", parent=styles["Normal"], fontSize=10, leading=14)
        code_style = ParagraphStyle("Code", parent=styles["Code"], fontSize=8, backColor=colors.HexColor("#f5f5f5"),
                                    leftIndent=12, rightIndent=12, borderPad=4)

        SEV_COLORS = {
            "CRITICAL": colors.HexColor("#d32f2f"),
            "HIGH": colors.HexColor("#f44336"),
            "MEDIUM": colors.HexColor("#ff9800"),
            "LOW": colors.HexColor("#2196f3"),
            "INFO": colors.HexColor("#9e9e9e"),
        }

        story = []
        meta = ctx["meta"]
        counts = ctx["counts"]

        # ── Cover ──────────────────────────────────────────────────────────────
        story.append(Spacer(1, 0.5*inch))
        story.append(Paragraph("🛡️ BugScanner Security Assessment Report", title_style))
        story.append(Spacer(1, 0.2*inch))
        story.append(HRFlowable(width="100%", thickness=2, color=colors.HexColor("#1565c0")))
        story.append(Spacer(1, 0.2*inch))

        meta_data = [
            ["Target", meta.get("target", "N/A")],
            ["Assessment Date", ctx["report_date"]],
            ["Scanner Version", meta.get("scanner_version", "1.0.0")],
            ["Overall Risk", ctx["overall_risk"]],
            ["Total Findings", str(ctx["total"])],
            ["Duration", f"{meta.get('duration_seconds', 0):.2f}s"],
        ]
        meta_table = Table(meta_data, colWidths=[2*inch, 4*inch])
        meta_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#e3f2fd")),
            ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 10),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#90caf9")),
            ("ROWBACKGROUNDS", (0, 0), (-1, -1), [colors.white, colors.HexColor("#fafafa")]),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("LEFTPADDING", (0, 0), (-1, -1), 8),
        ]))
        story.append(meta_table)
        story.append(Spacer(1, 0.3*inch))

        # ── Summary table ──────────────────────────────────────────────────────
        story.append(Paragraph("Executive Summary", h1_style))
        story.append(Spacer(1, 0.1*inch))

        summary_data = [["Severity", "Count"]] + [
            [sev, str(counts[sev])] for sev in ["CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO"]
        ]
        sum_table = Table(summary_data, colWidths=[2*inch, 1.5*inch])
        sum_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1565c0")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 10),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
            ("ALIGN", (1, 0), (1, -1), "CENTER"),
        ]))
        story.append(sum_table)
        story.append(Spacer(1, 0.4*inch))

        # ── Findings ───────────────────────────────────────────────────────────
        story.append(Paragraph("Technical Findings", h1_style))
        story.append(Spacer(1, 0.1*inch))

        for i, finding in enumerate(ctx["findings"], 1):
            sev = finding.get("severity", "INFO")
            sev_color = SEV_COLORS.get(sev, colors.grey)

            block = []
            title_para = Paragraph(
                f'<font color="#{sev_color.hexval()[2:]}">[{sev}]</font> '
                f'{i}. {finding.get("title", "Unknown")}',
                h2_style,
            )
            block.append(title_para)
            block.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#e0e0e0")))
            block.append(Spacer(1, 0.05*inch))

            detail_data = [
                ["CVSS Score", f"{finding.get('cvss_score', 0.0):.1f}", "OWASP", finding.get("owasp", "")],
                ["CWE", finding.get("cwe", ""), "Confirmed", "✅ Yes" if finding.get("confirmed") else "⚠️ Potential"],
                ["URL", finding.get("url", "")[:60], "Parameter", finding.get("parameter", "")[:30]],
            ]
            d_table = Table(detail_data, colWidths=[1.2*inch, 2.8*inch, 1.2*inch, 1.8*inch])
            d_table.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#f5f5f5")),
                ("BACKGROUND", (2, 0), (2, -1), colors.HexColor("#f5f5f5")),
                ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
                ("FONTNAME", (2, 0), (2, -1), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, -1), 9),
                ("GRID", (0, 0), (-1, -1), 0.3, colors.HexColor("#bdbdbd")),
                ("LEFTPADDING", (0, 0), (-1, -1), 6),
            ]))
            block.append(d_table)
            block.append(Spacer(1, 0.1*inch))

            for section, key in [("Description", "description"), ("Impact", "impact"), ("Remediation", "remediation")]:
                block.append(Paragraph(f"<b>{section}</b>", body_style))
                text = finding.get(key, "")
                # Escape HTML chars
                text = text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
                block.append(Paragraph(text, body_style))
                block.append(Spacer(1, 0.05*inch))

            # Payload
            payload = finding.get("payload", "")
            if payload:
                block.append(Paragraph("<b>Payload</b>", body_style))
                payload_safe = payload[:200].replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
                block.append(Paragraph(payload_safe, code_style))
                block.append(Spacer(1, 0.05*inch))

            block.append(Spacer(1, 0.2*inch))
            story.append(KeepTogether(block))

        # ── Remediation checklist ───────────────────────────────────────────────
        story.append(Paragraph("Remediation Checklist", h1_style))
        story.append(Spacer(1, 0.1*inch))

        chk_data = [["#", "Finding", "Severity", "Status"]]
        for i, f in enumerate(ctx["findings"], 1):
            chk_data.append([
                str(i),
                f.get("title", "")[:55],
                f.get("severity", ""),
                "☐ Open",
            ])
        chk_table = Table(chk_data, colWidths=[0.4*inch, 3.8*inch, 1*inch, 1*inch])
        chk_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1565c0")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 9),
            ("GRID", (0, 0), (-1, -1), 0.3, colors.grey),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#fafafa")]),
        ]))
        story.append(chk_table)
        story.append(Spacer(1, 0.3*inch))
        story.append(Paragraph(
            f"Report generated by BugScanner v{meta.get('scanner_version', '1.0.0')} | {ctx['report_date']}",
            ParagraphStyle("footer", parent=styles["Normal"], fontSize=8, textColor=colors.grey, alignment=TA_CENTER)
        ))

        doc.build(story)
        return out_path

    def _generate_html_fallback(self, ctx: dict) -> str:
        """Minimal HTML fallback for PDF generation."""
        SEV_COLORS = {
            "CRITICAL": "#d32f2f", "HIGH": "#f44336",
            "MEDIUM": "#ff9800", "LOW": "#2196f3", "INFO": "#9e9e9e",
        }
        meta = ctx["meta"]
        findings_html = ""
        for i, f in enumerate(ctx["findings"], 1):
            sev = f.get("severity", "INFO")
            clr = SEV_COLORS.get(sev, "#9e9e9e")
            findings_html += f"""
            <div class="finding">
                <h3><span style="color:{clr}">[{sev}]</span> {i}. {f.get('title', '')}</h3>
                <table><tr><td><b>CVSS</b></td><td>{f.get('cvss_score', 0):.1f}</td>
                <td><b>OWASP</b></td><td>{f.get('owasp', '')}</td>
                <td><b>CWE</b></td><td>{f.get('cwe', '')}</td></tr></table>
                <p><b>URL:</b> <code>{f.get('url', '')}</code></p>
                <p><b>Description:</b> {f.get('description', '')}</p>
                <p><b>Impact:</b> {f.get('impact', '')}</p>
                <p><b>Remediation:</b> {f.get('remediation', '')}</p>
                <p><b>Payload:</b> <code>{f.get('payload', '')[:200]}</code></p>
                <hr/>
            </div>"""

        return f"""<!DOCTYPE html>
<html><head><meta charset="utf-8">
<style>
body {{font-family: Arial,sans-serif; font-size:12px; margin:40px; color:#333;}}
h1 {{color:#1a237e;}} h2 {{color:#1565c0;}} h3 {{color:#1976d2;}}
table {{border-collapse:collapse; width:100%;}}
td,th {{border:1px solid #ddd; padding:6px;}}
.finding {{margin-bottom:24px; padding:12px; border-left:4px solid #1565c0;}}
code {{background:#f5f5f5; padding:2px 6px; font-family:monospace; font-size:11px;}}
</style></head><body>
<h1>BugScanner Security Report</h1>
<p><b>Target:</b> {meta.get('target', '')}</p>
<p><b>Date:</b> {ctx['report_date']}</p>
<p><b>Total Findings:</b> {ctx['total']} | <b>Overall Risk:</b> {ctx['overall_risk']}</p>
<hr/>
<h2>Technical Findings</h2>
{findings_html}
<p><i>Generated by BugScanner v{meta.get('scanner_version', '1.0.0')}</i></p>
</body></html>"""
