"""
╔══════════════════════════════════════════════════════════════════════════╗
║  BugScanner — Reconnaissance Module                                      ║
║  Author : Muhammad Faizan (faizzyhon@gmail.com)                          ║
║  Covers : IP resolution, DNS records, Whois, geolocation,                ║
║           HTTP header fingerprinting, WAF detection                      ║
╚══════════════════════════════════════════════════════════════════════════╝
"""

import json
import re
import socket
import ssl
import time
from datetime import datetime
from typing import Optional
from urllib.parse import urlparse

import requests
from rich.console import Console

from .base import BaseScanner, Finding

console = Console(stderr=True)

# ── Optional deps (graceful fallback if not installed) ────────────────────────

try:
    import dns.resolver
    DNS_AVAILABLE = True
except ImportError:
    DNS_AVAILABLE = False

try:
    import whois as _whois_lib
    WHOIS_AVAILABLE = True
except ImportError:
    WHOIS_AVAILABLE = False

# ── WAF fingerprints ─────────────────────────────────────────────────────────

WAF_SIGNATURES = {
    "Cloudflare": {
        "headers": ["cf-ray", "cf-cache-status", "cf-request-id", "__cfduid"],
        "body":    ["cloudflare", "Attention Required! | Cloudflare"],
    },
    "AWS WAF": {
        "headers": ["x-amzn-requestid", "x-amz-cf-id", "x-amz-id-2"],
        "body":    ["aws-waf", "AmazonAWS"],
    },
    "Akamai": {
        "headers": ["x-akamai-transformed", "x-check-cacheable", "akamai-origin-hop"],
        "body":    ["akamai", "AkamaiGHost"],
    },
    "ModSecurity": {
        "headers": ["mod_security", "modsecurity"],
        "body":    ["ModSecurity", "This error was generated by Mod_Security"],
    },
    "Sucuri": {
        "headers": ["x-sucuri-id", "x-sucuri-cache"],
        "body":    ["sucuri", "Access Denied - Sucuri Website Firewall"],
    },
    "Imperva / Incapsula": {
        "headers": ["x-iinfo", "x-cdn"],
        "body":    ["incapsula", "Incapsula incident"],
    },
    "F5 BIG-IP ASM": {
        "headers": ["x-cnection", "x-wa-info"],
        "body":    ["The requested URL was rejected", "F5 BIG-IP"],
    },
    "Nginx WAF": {
        "headers": [],
        "body":    ["nginx WAF", "naxsi"],
    },
    "Wordfence": {
        "headers": [],
        "body":    ["wordfence", "Generated by Wordfence"],
    },
    "Barracuda": {
        "headers": ["barra_counter_session"],
        "body":    ["barracuda"],
    },
}

# ── Geolocation via ip-api.com (free, no key) ────────────────────────────────

GEOIP_URL = "http://ip-api.com/json/{ip}?fields=status,country,countryCode,region,city,isp,org,as,query"


class ReconScanner(BaseScanner):
    """
    Phase-0 recon scanner — runs BEFORE all vulnerability tests.

    Outputs:
      • INFO  findings for DNS / Whois / geolocation data
      • LOW   findings for exposed server banners
      • INFO  special RECON_JSON: <json> line consumed by web_gui for the Recon tab
    """

    SCANNER_NAME    = "Reconnaissance"
    OWASP_CATEGORY  = "A05:2021"
    CWE             = "CWE-200"

    def run(self) -> list[Finding]:
        parsed  = urlparse(self.target)
        self.host   = parsed.hostname or ""
        self.scheme = parsed.scheme

        console.print(f"[bold cyan]🔍 RECON:[/bold cyan] Gathering intelligence on [green]{self.host}[/green]")

        recon: dict = {
            "host":       self.host,
            "target":     self.target,
            "scan_time":  datetime.utcnow().isoformat(),
        }

        recon["ip"]           = self._resolve_ip()
        recon["rdns"]         = self._reverse_dns(recon["ip"])
        recon["geo"]          = self._geolocate(recon["ip"])
        recon["dns"]          = self._dns_records()
        recon["whois"]        = self._whois_lookup()
        recon["http_headers"] = self._http_headers()
        recon["ssl"]          = self._ssl_info()
        recon["waf"]          = self._detect_waf(recon["http_headers"])

        self._emit_recon_json(recon)
        self._make_findings(recon)

        return [f.to_dict() if hasattr(f, "to_dict") else f for f in self.findings]

    # ─── Core data gathering ─────────────────────────────────────────────────

    def _resolve_ip(self) -> str:
        try:
            ip = socket.gethostbyname(self.host)
            console.print(f"  [green]✓[/green] IP: [cyan]{ip}[/cyan]")
            return ip
        except socket.gaierror as e:
            console.print(f"  [yellow]![/yellow] IP resolution failed: {e}")
            return ""

    def _reverse_dns(self, ip: str) -> str:
        if not ip:
            return ""
        try:
            return socket.gethostbyaddr(ip)[0]
        except Exception:
            return ""

    def _geolocate(self, ip: str) -> dict:
        if not ip or ip.startswith(("127.", "10.", "192.168.", "172.")):
            return {"country": "Local/Private", "city": "", "isp": ""}
        try:
            r = requests.get(GEOIP_URL.format(ip=ip), timeout=6)
            data = r.json()
            if data.get("status") == "success":
                geo = {
                    "country":  data.get("country", ""),
                    "code":     data.get("countryCode", ""),
                    "region":   data.get("region", ""),
                    "city":     data.get("city", ""),
                    "isp":      data.get("isp", ""),
                    "org":      data.get("org", ""),
                    "asn":      data.get("as", ""),
                }
                console.print(
                    f"  [green]✓[/green] Geo: [cyan]{geo['city']}, {geo['country']}[/cyan] "
                    f"| ISP: [dim]{geo['isp']}[/dim]"
                )
                return geo
        except Exception:
            pass
        return {}

    def _dns_records(self) -> dict:
        records: dict = {}
        if not DNS_AVAILABLE:
            # Fallback: basic A record only
            try:
                records["A"] = [socket.gethostbyname(self.host)]
            except Exception:
                pass
            return records

        record_types = ["A", "AAAA", "MX", "NS", "TXT", "CNAME", "SOA"]
        for rtype in record_types:
            try:
                answers = dns.resolver.resolve(self.host, rtype, lifetime=4)
                records[rtype] = [str(r) for r in answers]
            except Exception:
                pass

        if records:
            console.print(f"  [green]✓[/green] DNS: {', '.join(records.keys())} records found")
        return records

    def _whois_lookup(self) -> dict:
        if not WHOIS_AVAILABLE:
            return {"note": "python-whois not installed; run: pip install python-whois"}
        try:
            w = _whois_lib.whois(self.host)
            result = {
                "registrar":       str(w.registrar or ""),
                "creation_date":   str(w.creation_date or ""),
                "expiration_date": str(w.expiration_date or ""),
                "name_servers":    [str(ns) for ns in (w.name_servers or [])],
                "org":             str(w.org or ""),
                "country":         str(w.country or ""),
                "emails":          [str(e) for e in (w.emails if isinstance(w.emails, list) else [w.emails] if w.emails else [])],
            }
            console.print(f"  [green]✓[/green] Whois: registrar=[cyan]{result['registrar'][:40]}[/cyan]")
            return result
        except Exception as e:
            return {"error": str(e)}

    def _http_headers(self) -> dict:
        try:
            r = requests.get(
                self.target, timeout=10, verify=False,
                allow_redirects=True,
                headers={"User-Agent": "Mozilla/5.0 BugScanner/1.0"},
            )
            headers = dict(r.headers)
            # Normalise keys to lowercase
            headers_lower = {k.lower(): v for k, v in headers.items()}
            console.print(
                f"  [green]✓[/green] HTTP {r.status_code} | "
                f"Server: [cyan]{headers_lower.get('server', 'unknown')}[/cyan]"
            )
            return headers_lower
        except Exception as e:
            console.print(f"  [yellow]![/yellow] HTTP headers fetch failed: {e}")
            return {}

    def _ssl_info(self) -> dict:
        if self.scheme != "https":
            return {}
        try:
            ctx  = ssl.create_default_context()
            conn = ctx.wrap_socket(
                socket.create_connection((self.host, 443), timeout=6),
                server_hostname=self.host,
            )
            cert = conn.getpeercert()
            conn.close()
            san_list = []
            for stype, sval in cert.get("subjectAltName", []):
                if stype == "DNS":
                    san_list.append(sval)
            issuer = dict(x[0] for x in cert.get("issuer", []))
            subject = dict(x[0] for x in cert.get("subject", []))
            return {
                "subject":    subject.get("commonName", ""),
                "issuer":     issuer.get("organizationName", ""),
                "not_before": cert.get("notBefore", ""),
                "not_after":  cert.get("notAfter", ""),
                "san":        san_list[:20],
                "version":    cert.get("version", ""),
            }
        except ssl.SSLCertVerificationError:
            return {"error": "SSL certificate verification failed — possible self-signed cert"}
        except Exception as e:
            return {"error": str(e)}

    def _detect_waf(self, headers: dict) -> list[str]:
        waf_detected = []
        try:
            probe_url = f"{self.target}/?WAF_TEST=<script>alert(1)</script>"
            r = requests.get(
                probe_url, timeout=8, verify=False,
                allow_redirects=True,
                headers={"User-Agent": "Mozilla/5.0"},
            )
            body_lower = r.text.lower()
            all_headers_lower = {k.lower(): v.lower() for k, v in r.headers.items()}
        except Exception:
            body_lower = ""
            all_headers_lower = headers

        for waf_name, sigs in WAF_SIGNATURES.items():
            matched = False
            for h in sigs.get("headers", []):
                if h.lower() in all_headers_lower:
                    matched = True
                    break
            if not matched:
                for pattern in sigs.get("body", []):
                    if pattern.lower() in body_lower:
                        matched = True
                        break
            if matched:
                waf_detected.append(waf_name)

        if waf_detected:
            console.print(f"  [yellow]🛡[/yellow] WAF detected: [yellow]{', '.join(waf_detected)}[/yellow]")
        else:
            console.print("  [dim]No WAF detected (or WAF is transparent)[/dim]")
        return waf_detected

    # ─── Emit structured data ─────────────────────────────────────────────────

    def _emit_recon_json(self, recon: dict):
        """
        Print a special RECON_JSON: line that web_gui.py's _detect_finding()
        will intercept and send as a 'recon_data' SSE event to the browser.
        """
        print(f"RECON_JSON:{json.dumps(recon)}", flush=True)

    # ─── Create Finding objects ───────────────────────────────────────────────

    def _make_findings(self, recon: dict):
        # Server banner disclosure
        server = recon.get("http_headers", {}).get("server", "")
        if server:
            self.add_finding(Finding(
                title=f"Server Banner Disclosure: {server[:60]}",
                severity="LOW",
                owasp="A05:2021",
                cwe="CWE-200",
                cvss_score=3.1,
                cvss_vector="CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N",
                url=self.target,
                description=(
                    f"The web server discloses its banner: `{server}`. "
                    "This information assists attackers in identifying the server software and version, "
                    "enabling targeted exploitation of known CVEs."
                ),
                impact="Enables targeted attacks against known server vulnerabilities.",
                remediation=(
                    "Configure your web server to suppress or obscure the Server header. "
                    "For Nginx: `server_tokens off;` | For Apache: `ServerTokens Prod; ServerSignature Off`"
                ),
                confirmed=True,
                vuln_type="info_disclosure",
            ))

        # X-Powered-By disclosure
        powered_by = recon.get("http_headers", {}).get("x-powered-by", "")
        if powered_by:
            self.add_finding(Finding(
                title=f"Technology Disclosure via X-Powered-By: {powered_by[:50]}",
                severity="LOW",
                owasp="A05:2021",
                cwe="CWE-200",
                cvss_score=2.6,
                cvss_vector="CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N",
                url=self.target,
                description=f"The `X-Powered-By` header reveals: `{powered_by}`.",
                impact="Reveals backend technology stack to attackers.",
                remediation="Remove the X-Powered-By header. In PHP: `expose_php = Off` in php.ini.",
                confirmed=True,
                vuln_type="info_disclosure",
            ))

        # WAF detected — informational
        wafs = recon.get("waf", [])
        if wafs:
            self.add_finding(Finding(
                title=f"WAF Detected: {', '.join(wafs)}",
                severity="INFO",
                owasp="A05:2021",
                cwe="CWE-693",
                cvss_score=0.0,
                cvss_vector="",
                url=self.target,
                description=(
                    f"A Web Application Firewall was detected: {', '.join(wafs)}. "
                    "Some attack payloads may be blocked; try WAF bypass techniques if testing further."
                ),
                impact="Reduces attack surface but may be bypassable.",
                remediation="Ensure WAF rules are up to date and configured in blocking mode.",
                confirmed=True,
                vuln_type="info",
            ))

        # SSL expiry check
        ssl_info = recon.get("ssl", {})
        if ssl_info and "not_after" in ssl_info and ssl_info["not_after"]:
            try:
                from datetime import timezone
                expiry_str = ssl_info["not_after"]
                expiry     = datetime.strptime(expiry_str, "%b %d %H:%M:%S %Y %Z")
                days_left  = (expiry - datetime.utcnow()).days
                if days_left < 30:
                    self.add_finding(Finding(
                        title=f"SSL Certificate Expiring Soon ({days_left} days)",
                        severity="MEDIUM" if days_left < 14 else "LOW",
                        owasp="A02:2021",
                        cwe="CWE-295",
                        cvss_score=4.3 if days_left < 14 else 2.0,
                        cvss_vector="CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:L",
                        url=self.target,
                        description=f"SSL certificate expires on {expiry_str} ({days_left} days remaining).",
                        impact="Expired certificates cause browser warnings and break HTTPS.",
                        remediation="Renew the SSL/TLS certificate immediately.",
                        confirmed=True,
                        vuln_type="ssl",
                    ))
            except Exception:
                pass

        # SSL cert verification error → self-signed
        if ssl_info.get("error") and "verification" in ssl_info.get("error", "").lower():
            self.add_finding(Finding(
                title="SSL Certificate Verification Failure (possible self-signed cert)",
                severity="MEDIUM",
                owasp="A02:2021",
                cwe="CWE-295",
                cvss_score=5.9,
                cvss_vector="CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:N/A:N",
                url=self.target,
                description="The SSL certificate failed verification, suggesting it may be self-signed or expired.",
                impact="Exposes users to MITM attacks due to untrusted certificate.",
                remediation="Deploy a CA-signed certificate from a trusted authority (e.g. Let's Encrypt).",
                confirmed=True,
                vuln_type="ssl",
            ))
